---
title: ""
author: ""
date:""
output: html_document
---
# 1
```{r}
#Auto path
#install.packages("here")
library(here)
pathh <- here("I", "transformado.xlsx")

#manual path
#pathh <- r'{}'
#install.packages("readxl")

#get dataframe
data <- readxl::read_excel(pathh)
class(data)
```
# 2
```{r}
"pTudoPrejudica" -> colnames(data)[which(names(data) == "v12")]
"pPreocuparDemasiado" -> colnames(data)[which(names(data) == "v13")]
"pCrescimentoEconomicoPos" -> colnames(data)[which(names(data) == "v14")]
"pAnimaisExperiencias" -> colnames(data)[which(names(data) == "v15")]
"pCrescimentoEconomicoNeg" -> colnames(data)[which(names(data) == "v16")]
"pMundoMelhorar" -> colnames(data)[which(names(data) == "v72")]
colnames(data)
```
# 3
```{r}
#if yhey are empty
#Omissos <- is.na(data$idade)

#if they are with a direct value of NA
Omissos <- data$idade == "NA"
which(Omissos)
```

# 4
```{r}
median(data$p) -> data$p[which(Omissos)]
```

# 5
```{r}
tab_sexo <- table(data$ sexo)
perc_tab_sexo <- prop.table(tab_sexo) * 100

tab_v15 <- table(data$ v15)
perc_tab_v15 <- prop.table(tab_v15) * 100

tab_v15_sexo <- table(data$ v15, data$ sexo)
perc_tab_v15_sexo <- prop.table(tab_v15_sexo) * 100

tab_sexo
perc_tab_sexo
tab_v15
perc_tab_v15
tab_v15_sexo
perc_tab_v15_sexo




```


